# Generated by Django 3.2.13 on 2022-07-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='left_school',
            field=models.BooleanField(default=False),
        ),
    ]
