# Generated by Django 3.2.13 on 2022-07-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20220718_0143'),
        ('teacher', '0002_teacher_left_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phone_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='FormTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_teacher_of', models.ManyToManyField(blank=True, to='student.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
