# Generated by Django 3.2.13 on 2022-07-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_class_unique_together'),
        ('teacher', '0004_remove_teacher_phone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
            preserve_default=False,
        ),
    ]
