# Generated by Django 3.2.13 on 2022-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20220811_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='management_team',
            field=models.BooleanField(default=False),
        ),
    ]
