# Generated by Django 3.2.13 on 2022-09-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
