# Generated by Django 3.2.13 on 2022-09-16 01:05

from django.db import migrations
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', management.models.MyUserManager()),
            ],
        ),
    ]
