# Generated by Django 3.2.13 on 2022-09-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspended',
        ),
    ]
