# Generated by Django 3.2.13 on 2022-07-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('mobile_phone', models.CharField(blank=True, max_length=150)),
                ('office_phone', models.CharField(blank=True, max_length=150)),
                ('full_postal_address', models.CharField(blank=True, max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('business_address', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date_of_entry', models.CharField(blank=True, max_length=150)),
                ('session', models.CharField(blank=True, max_length=150)),
                ('term', models.CharField(blank=True, max_length=150)),
                ('medical_conditions', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('state_of_origin', models.CharField(blank=True, max_length=150)),
                ('birth_day', models.CharField(blank=True, max_length=150)),
                ('birth_month', models.CharField(blank=True, max_length=150)),
                ('mobile_phone', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('office_phone', models.CharField(blank=True, max_length=150)),
                ('full_postal_address', models.CharField(blank=True, max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('business_address', models.CharField(blank=True, max_length=150)),
                ('blood_group', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('mobile_phone', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('office_phone', models.CharField(blank=True, max_length=150)),
                ('full_postal_address', models.CharField(blank=True, max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('business_address', models.CharField(blank=True, max_length=150)),
                ('relationship_to_child', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HowDidYouHearAboutCDSSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.CharField(blank=True, max_length=255)),
                ('referrer_name', models.CharField(blank=True, max_length=150)),
                ('referrer_phone_number', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('state_of_origin', models.CharField(blank=True, max_length=150)),
                ('birth_day', models.CharField(blank=True, max_length=150)),
                ('birth_month', models.CharField(blank=True, max_length=150)),
                ('mobile_phone', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('office_phone', models.CharField(blank=True, max_length=150)),
                ('full_postal_address', models.CharField(blank=True, max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('business_address', models.CharField(blank=True, max_length=150)),
                ('blood_group', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school', models.CharField(blank=True, max_length=150)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('head_teacher_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=150)),
                ('student_class1', models.CharField(blank=True, max_length=150)),
                ('date_of_birth1', models.DateField(blank=True)),
                ('name2', models.CharField(blank=True, max_length=150)),
                ('student_class2', models.CharField(blank=True, max_length=150)),
                ('date_of_birth2', models.DateField(blank=True)),
                ('name3', models.CharField(blank=True, max_length=150)),
                ('student_class3', models.CharField(blank=True, max_length=150)),
                ('date_of_birth3', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=150)),
                ('religion', models.CharField(blank=True, max_length=150)),
                ('child_current_address', models.CharField(blank=True, max_length=150)),
                ('currently_resides_with', models.CharField(blank=True, max_length=150)),
                ('left_school', models.BooleanField(default=False)),
                ('emergency_contact_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.emergencycontactdetail')),
                ('entry_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.entrydetails')),
                ('father', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.father')),
                ('guardian', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.guardian')),
                ('how_did_you_hear_about_CDSSE', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.howdidyouhearaboutcdsse')),
                ('mother', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.mother')),
                ('previous_school_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.previousschooldetail')),
                ('siblings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.siblings')),
            ],
        ),
    ]
