# Generated by Django 3.2.13 on 2022-07-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220716_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.parent'),
        ),
    ]
