# Generated by Django 3.2.13 on 2022-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20220716_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
