# Generated by Django 3.2.13 on 2022-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220716_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='student.Parent'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_section', models.CharField(blank=True, max_length=255, unique=True)),
                ('the_class', models.CharField(blank=True, max_length=150)),
                ('subject', models.ManyToManyField(blank=True, null=True, to='student.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='student.Subject'),
        ),
    ]
