# Generated by Django 3.2.13 on 2022-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20220717_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, to='student.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='parent', to='student.Parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, to='student.Subject'),
        ),
    ]
