# Generated by Django 3.2.13 on 2022-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20220718_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='the_section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
