# Generated by Django 3.2.13 on 2022-07-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_class_the_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('the_section', 'the_class')},
        ),
    ]
