# Generated by Django 3.2.13 on 2022-08-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_class_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=150, unique=True)),
                ('exam_session', models.CharField(max_length=150, unique=True)),
                ('exam_term', models.CharField(max_length=150, unique=True)),
                ('exam_starts', models.CharField(max_length=150, unique=True)),
                ('exam_ends', models.CharField(max_length=150, unique=True)),
                ('next_term_begins', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(max_length=150, unique=True)),
                ('period', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(max_length=150, unique=True)),
                ('subject', models.CharField(max_length=150, unique=True)),
                ('session', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
