# Generated by Django 3.2.13 on 2022-08-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_exam_passmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='comment',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='next_term_ends',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
