# Generated by Django 3.2.13 on 2022-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20220802_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='comment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_ends',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_session',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_starts',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_term',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='next_term_begins',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='next_term_ends',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passmark',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passmark',
            name='mark',
            field=models.FloatField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passmark',
            name='period',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passmark',
            name='session',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passmark',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
