# Generated by Django 3.2.13 on 2022-08-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20220803_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
