# Generated by Django 3.2.13 on 2022-08-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmark',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
    ]
