# Generated by Django 3.2.13 on 2022-08-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_passmark_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetails',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.session'),
        ),
    ]
