# Generated by Django 3.2.13 on 2022-08-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_entrydetails_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.class'),
        ),
    ]
