# Generated by Django 3.2.13 on 2022-08-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ExactClass',
            fields=[
                ('the_class', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False)),
                ('subject', models.ManyToManyField(blank=True, to='student.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='class',
            name='the_class',
        ),
        migrations.RemoveField(
            model_name='class',
            name='the_section',
        ),
    ]
