# Generated by Django 3.2.13 on 2022-08-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20220811_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.exactclass'),
        ),
        migrations.AddField(
            model_name='class',
            name='the_section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('the_section', 'the_class')},
        ),
    ]
