# Generated by Django 3.2.13 on 2022-08-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20220811_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExactClass',
            new_name='JustClass',
        ),
    ]
