# Generated by Django 3.2.13 on 2022-08-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_rename_exactclass_justclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmark',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
