# Generated by Django 3.2.13 on 2022-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_alter_passmark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='comment',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
