# Generated by Django 3.2.13 on 2022-09-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
