# Generated by Django 3.2.13 on 2022-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0002_auto_20220724_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField(blank=True, max_length=3000)),
                ('left_school', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField(blank=True, max_length=3000)),
                ('left_school', models.BooleanField(default=False)),
            ],
        ),
    ]
