# Generated by Django 3.2.13 on 2022-07-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0003_accountant_libarian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libarian',
            new_name='Librarian',
        ),
    ]
