# Generated by Django 3.2.13 on 2022-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0004_rename_libarian_librarian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semiadmin',
            old_name='passport_photo',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='semiadmin',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='semiadmin',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='semiadmin',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='semiadmin',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='semiadmin',
            name='religion',
        ),
        migrations.AddField(
            model_name='semiadmin',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='semiadmin',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='semiadmin',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
