# Generated by Django 3.2.13 on 2022-07-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_class_unique_together'),
        ('teacher', '0004_remove_teacher_phone_phone'),
        ('semiadmin', '0005_auto_20220725_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheetFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('session', models.CharField(blank=True, max_length=255)),
                ('ca1_ca2_ca3_ca4_exam60', models.BooleanField(default=False)),
                ('ca1_ca2_ca3_exam70', models.BooleanField(default=False)),
                ('ca1_ca2_exam70', models.BooleanField(default=False)),
                ('ca1_exam70', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.BooleanField(default=False)),
                ('assignment', models.BooleanField(default=False)),
                ('mid_term', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('online_exam', models.BooleanField(default=False)),
                ('the_exact_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class')),
                ('the_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('the_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='MarkSheet',
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='marksheet_format_entrys',
            field=models.ManyToManyField(blank=True, to='semiadmin.MarkSheetFormat'),
        ),
    ]
