# Generated by Django 3.2.13 on 2022-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0006_auto_20220725_1711'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marksheetformat',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ca1_ca2_ca3_ca4_exam60', True), ('ca1_ca2_ca3_exam70', False), ('ca1_ca2_exam70', False), ('ca1_exam70', False)), models.Q(('ca1_ca2_ca3_ca4_exam60', False), ('ca1_ca2_ca3_exam70', True), ('ca1_ca2_exam70', False), ('ca1_exam70', False)), models.Q(('ca1_ca2_ca3_ca4_exam60', False), ('ca1_ca2_ca3_exam70', False), ('ca1_ca2_exam70', True), ('ca1_exam70', False)), models.Q(('ca1_ca2_ca3_ca4_exam60', False), ('ca1_ca2_ca3_exam70', False), ('ca1_ca2_exam70', False), ('ca1_exam70', True)), _connector='OR'), name='check_one_true_from_booleans'),
        ),
    ]
