# Generated by Django 3.2.13 on 2022-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0007_marksheetformat_check_one_true_from_booleans'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marksheetformat',
            name='check_one_true_from_booleans',
        ),
        migrations.RemoveField(
            model_name='marksheetformat',
            name='ca1_ca2_ca3_ca4_exam60',
        ),
        migrations.RemoveField(
            model_name='marksheetformat',
            name='ca1_ca2_ca3_exam70',
        ),
        migrations.RemoveField(
            model_name='marksheetformat',
            name='ca1_ca2_exam70',
        ),
        migrations.RemoveField(
            model_name='marksheetformat',
            name='ca1_exam70',
        ),
        migrations.AddField(
            model_name='marksheetformat',
            name='format',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='marksheetformat',
            constraint=models.CheckConstraint(check=models.Q(('format', 'two_column_format'), ('format', 'three_column_format'), ('format', 'four_column_format'), ('format', 'five_column_format'), _connector='OR'), name='check_one_true_from_booleans'),
        ),
    ]
