# Generated by Django 3.2.13 on 2022-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0008_auto_20220729_1152'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marksheetformat',
            name='check_one_true_from_booleans',
        ),
        migrations.RenameField(
            model_name='marksheetformat',
            old_name='format',
            new_name='mark_format',
        ),
        migrations.AddConstraint(
            model_name='marksheetformat',
            constraint=models.CheckConstraint(check=models.Q(('mark_format', 'two_column_format'), ('mark_format', 'three_column_format'), ('mark_format', 'four_column_format'), ('mark_format', 'five_column_format'), _connector='OR'), name='check_one_true_from_booleans'),
        ),
    ]
