# Generated by Django 3.2.13 on 2022-07-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0010_auto_20220729_1245'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marksheetformat',
            name='check_mark_format',
        ),
        migrations.AlterUniqueTogether(
            name='marksheetformat',
            unique_together={('category', 'session', 'mark_format')},
        ),
        migrations.AddConstraint(
            model_name='marksheetformat',
            constraint=models.CheckConstraint(check=models.Q(('mark_format', 'two_column_format'), ('mark_format', 'three_column_format'), ('mark_format', 'four_column_format'), ('mark_format', 'five_column_format'), ('mark_format', ''), _connector='OR'), name='check_mark_format'),
        ),
    ]
