# Generated by Django 3.2.13 on 2022-08-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_subject'),
        ('student', '0013_alter_class_unique_together'),
        ('semiadmin', '0012_auto_20220730_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectpermission',
            name='the_exact_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.class'),
        ),
        migrations.AlterField(
            model_name='subjectpermission',
            name='the_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
        migrations.AlterField(
            model_name='subjectpermission',
            name='the_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
