# Generated by Django 3.2.13 on 2022-08-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0013_auto_20220801_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageCognitiveDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_type', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
