# Generated by Django 3.2.13 on 2022-08-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_passmark_subject'),
        ('semiadmin', '0014_managecognitivedomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveKeyDomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HousemasterCommentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('code_number', models.CharField(blank=True, max_length=255)),
                ('code_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalCommentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('code_number', models.CharField(blank=True, max_length=255)),
                ('code_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCommentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('code_number', models.CharField(blank=True, max_length=255)),
                ('code_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalSubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('Subject_code', models.CharField(blank=True, max_length=255)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
