# Generated by Django 3.2.13 on 2022-08-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0015_cognitivekeydomainscore_housemastercommentcode_principalcommentcode_principalsubjectcode_teachercomm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognitivekeydomainscore',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
