# Generated by Django 3.2.13 on 2022-08-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0016_alter_cognitivekeydomainscore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principalsubjectcode',
            old_name='Subject_code',
            new_name='subject_code',
        ),
    ]
