# Generated by Django 3.2.13 on 2022-08-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0019_alter_marksheetformat_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='the_class',
            new_name='class_room',
        ),
    ]
