# Generated by Django 3.2.13 on 2022-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0020_rename_the_class_mark_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='test30',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
