# Generated by Django 3.2.13 on 2022-08-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0022_mark_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='assignment10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam70',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mid_test10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mid_test15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='project10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='resumption_test10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='resumption_test15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='test30',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
