# Generated by Django 3.2.13 on 2022-08-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0023_auto_20220809_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='assignment10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam60',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam70',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mid_test10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mid_test15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='project10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='resumption_test10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='resumption_test15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='test30',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
