# Generated by Django 3.2.13 on 2022-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0024_auto_20220809_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('grade_point', models.CharField(blank=True, max_length=255)),
                ('mark_from', models.CharField(blank=True, max_length=255)),
                ('mark_upto', models.CharField(blank=True, max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
