# Generated by Django 3.2.13 on 2022-08-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0026_book_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=255),
        ),
    ]
