# Generated by Django 3.2.13 on 2022-08-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0028_expensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('the_date', models.DateField(auto_now_add=True)),
                ('expense_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.expensecategory')),
            ],
        ),
    ]
