# Generated by Django 3.2.13 on 2022-08-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_rename_exactclass_justclass'),
        ('semiadmin', '0029_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.IntegerField(blank=True)),
                ('paid_amount', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('the_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
    ]
