# Generated by Django 3.2.13 on 2022-08-15 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0030_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='the_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
