# Generated by Django 3.2.13 on 2022-08-15 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0033_rename_eventcalender_eventcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcalendar',
            name='ending_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='starting_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
