# Generated by Django 3.2.13 on 2022-08-18 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0034_auto_20220815_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='the_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
