# Generated by Django 3.2.13 on 2022-08-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20220811_2240'),
        ('semiadmin', '0035_alter_expense_the_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.department'),
        ),
    ]
