# Generated by Django 3.2.13 on 2022-08-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_exam_comment'),
        ('semiadmin', '0036_alter_managementteam_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honesty', models.IntegerField(blank=True, null=True)),
                ('neatness', models.IntegerField(blank=True, null=True)),
                ('punctuality', models.IntegerField(blank=True, null=True)),
                ('attentiveness_in_class', models.IntegerField(blank=True, null=True)),
                ('organizational_ability', models.IntegerField(blank=True, null=True)),
                ('perseverance', models.IntegerField(blank=True, null=True)),
                ('self_control', models.IntegerField(blank=True, null=True)),
                ('arts_and_crafts', models.IntegerField(blank=True, null=True)),
                ('drawing_and_painting', models.IntegerField(blank=True, null=True)),
                ('labour_and_workshop', models.IntegerField(blank=True, null=True)),
                ('fluency', models.IntegerField(blank=True, null=True)),
                ('sport_and_gymnastics', models.IntegerField(blank=True, null=True)),
                ('handwriting', models.IntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.exam')),
                ('housemaster_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.housemastercommentcode')),
                ('principal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.principalcommentcode')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.principalsubjectcode')),
                ('teacher_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.teachercommentcode')),
            ],
        ),
    ]
