# Generated by Django 3.2.13 on 2022-08-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0038_auto_20220830_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdomainscore',
            name='subject_code',
            field=models.ManyToManyField(to='semiadmin.PrincipalSubjectCode'),
        ),
    ]
