# Generated by Django 3.2.13 on 2022-09-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20220811_2240'),
        ('student', '0028_alter_exam_comment'),
        ('semiadmin', '0039_alter_studentdomainscore_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdomainscore',
            name='housemaster_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.housemastercommentcode'),
        ),
        migrations.AlterField(
            model_name='studentdomainscore',
            name='principal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.principalcommentcode'),
        ),
        migrations.AlterField(
            model_name='studentdomainscore',
            name='subject_code',
            field=models.ManyToManyField(blank=True, to='semiadmin.PrincipalSubjectCode'),
        ),
        migrations.AlterField(
            model_name='studentdomainscore',
            name='teacher_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semiadmin.teachercommentcode'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=255)),
                ('starting_hour', models.CharField(blank=True, max_length=255)),
                ('starting_minute', models.CharField(blank=True, max_length=255)),
                ('ending_hour', models.CharField(blank=True, max_length=255)),
                ('ending_minute', models.CharField(blank=True, max_length=255)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('the_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
    ]
