# Generated by Django 3.2.13 on 2022-09-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_exam_comment'),
        ('semiadmin', '0040_auto_20220902_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('the_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
    ]
