# Generated by Django 3.2.13 on 2022-09-03 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0041_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='the_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
