# Generated by Django 3.2.13 on 2022-09-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0043_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
