# Generated by Django 3.2.13 on 2022-09-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0044_attendance_attended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementTeam',
        ),
    ]
