# Generated by Django 3.2.13 on 2022-09-09 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0045_delete_managementteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(blank=True, max_length=255)),
                ('excerpts', models.CharField(blank=True, max_length=255)),
                ('notice', models.TextField(blank=True, max_length=10000)),
                ('show_on_website', models.BooleanField(blank=True, default=True, null=True)),
                ('notice_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('the_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
