# Generated by Django 3.2.13 on 2022-09-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_exam_comment'),
        ('semiadmin', '0046_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_session_set', to='student.session')),
                ('next_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_session_set', to='student.session')),
                ('promoting_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoting_from_set', to='student.class')),
                ('promoting_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoting_to_set', to='student.class')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to='student.student')),
            ],
        ),
    ]
