# Generated by Django 3.2.13 on 2022-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiadmin', '0050_alter_semiadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam100',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
